# Generated by Django 5.2.17 on 2026-09-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de course')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('categorie', models.CharField(blank=True, choices=[('PLAT', 'Plat'), ('ATTELE', 'Attelé'), ('MONTE', 'Monté'), ('OBSTACLE', 'Obstacle'), ('AUTRE', 'Autre')], db_index=True, default='PLAT', max_length=20)),
                ('distance_metres', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance en mètres')),
                ('nombre_partants_prevu', models.PositiveIntegerField(blank=True, default=0)),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ prévue')),
                ('heure_depart_reelle', models.TimeField(blank=True, null=True, verbose_name='Heure de départ réelle')),
                ('statut', models.CharField(blank=True, choices=[('PROGRAMMEE', 'Programmée'), ('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('RESULTAT_PROVISOIRE', 'Résultat provisoire'), ('RESULTAT_OFFICIEL', 'Résultat officiel'), ('ANNULEE', 'Annulée'), ('REPORTEE', 'Reportée')], db_index=True, default='PROGRAMMEE', max_length=30)),
                ('est_active', models.BooleanField(db_index=True, default=True)),
                ('conditions', models.TextField(blank=True)),
                ('allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Entraineur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nom_complet', models.CharField(db_index=True, max_length=150, verbose_name='Nom complet')),
                ('pays', models.CharField(blank=True, default='Burkina Faso', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'entraineurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Hippodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('ville', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='Burkina Faso', max_length=100, verbose_name='Pays')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hippodromes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nom_complet', models.CharField(db_index=True, max_length=150, verbose_name='Nom complet')),
                ('pays', models.CharField(blank=True, default='Burkina Faso', max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('poids_reference_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'jockeys',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_enregistrement', models.CharField(blank=True, db_index=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('nom', models.CharField(db_index=True, max_length=150, verbose_name='Nom')),
                ('sexe', models.CharField(blank=True, choices=[('MALE', 'Mâle'), ('FEMELLE', 'Femelle'), ('CASTRE', 'Hongre'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=15)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('proprietaire', models.CharField(blank=True, max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('entraineur_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chevaux', to='hippisme.entraineur', verbose_name='Entraîneur actuel')),
            ],
            options={
                'db_table': 'chevaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Partant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro')),
                ('corde', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('cote', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('est_non_partant', models.BooleanField(db_index=True, default=False)),
                ('raison_non_partant', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('donnees_source', models.JSONField(blank=True, default=dict)),
                ('cheval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='hippisme.cheval', verbose_name='Cheval')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partants', to='hippisme.course', verbose_name='Course')),
                ('entraineur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='hippisme.entraineur', verbose_name='Entraîneur')),
                ('jockey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='hippisme.jockey', verbose_name='Jockey')),
            ],
            options={
                'db_table': 'partants',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('date_reunion', models.DateField(blank=True, db_index=True, null=True, verbose_name='Date de réunion')),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée'), ('REPORTEE', 'Reportée')], db_index=True, default='PROGRAMMEE', max_length=20)),
                ('nombre_courses_prevu', models.PositiveIntegerField(blank=True, default=0)),
                ('nombre_courses_terminees', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('hippodrome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='hippisme.hippodrome', verbose_name='Hippodrome')),
            ],
            options={
                'db_table': 'reunions',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='hippisme.reunion', verbose_name='Réunion'),
        ),
    ]
