# Generated by Django 5.2.17 on 2026-09-10 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hippisme', '0001_initial'),
        ('points_vente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_ticket', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Numéro du ticket')),
                ('type', models.CharField(choices=[('SIMPLE', 'Simple'), ('COUPLE', 'Couplé'), ('TIERCE', 'Tiercé'), ('QUARTE', 'Quarté'), ('QUINTE', 'Quinté'), ('AUTRE', 'Autre')], db_index=True, max_length=20)),
                ('montant_mise', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mise')),
                ('montant_gain', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gain')),
                ('selections', models.JSONField(default=list, verbose_name='Sélections')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('GAGNANT', 'Gagnant'), ('PERDANT', 'Perdant'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé'), ('VERIFIE', 'Vérifié')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('est_verifie', models.BooleanField(db_index=True, default=False)),
                ('date_prise', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.CharField(blank=True, max_length=255)),
                ('reference_externe', models.CharField(blank=True, db_index=True, max_length=100)),
                ('donnees_ticket', models.JSONField(blank=True, default=dict)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paris', to='hippisme.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL)),
                ('point_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paris', to='points_vente.pointvente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paris',
                'ordering': ['-date_prise'],
                'indexes': [models.Index(fields=['course', 'statut'], name='paris_course__1d1494_idx'), models.Index(fields=['point_vente', 'date_prise'], name='paris_point_v_3e5c6a_idx'), models.Index(fields=['est_verifie', 'statut'], name='paris_est_ver_18e2d7_idx'), models.Index(fields=['type', 'statut'], name='paris_type_37587d_idx')],
            },
        ),
    ]
