# Generated by Django 5.2.17 on 2026-09-10 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hippisme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('OFFICIEL', 'Officiel'), ('ANNULE', 'Annulé')], db_index=True, default='PROVISOIRE', max_length=20)),
                ('arrivee', models.JSONField(blank=True, default=list, help_text="Liste d'objets structurés : [{'rang': 1, 'cheval': '14'}, ...]", verbose_name='Arrivée ordonnée')),
                ('non_partants', models.CharField(blank=True, default='00', max_length=50, verbose_name='Non-partants (NP)')),
                ('rapports', models.JSONField(blank=True, default=dict, verbose_name='Rapports de gains')),
                ('temps_course', models.CharField(blank=True, max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('date_officialisation', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='Scraper LONAB', max_length=150)),
                ('donnees_brutes', models.JSONField(blank=True, default=dict, help_text='Copie brute du dictionnaire extrait du HTML/crawler')),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='hippisme.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resultats',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['statut', 'date_publication'], name='resultats_statut_ce632a_idx')],
            },
        ),
    ]
