# Generated by Django 5.2.17 on 2026-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='non_partants_ordre',
            field=models.CharField(blank=True, default='Aucun', max_length=100, verbose_name="Non-partants d'ordre (NPO)"),
        ),
    ]
