# Generated by Django 5.2.17 on 2026-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0002_resultat_non_partants_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='source',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('AUTOMATIQUE', 'Automatique'), ('API', 'API Externe'), ('SCRAPING_LONAB_BF', 'Scraping le site WEB de la LONAB')], db_index=True, default='MANUEL', max_length=20, verbose_name='Source des données'),
        ),
    ]
