# Generated by Django 5.2.17 on 2026-09-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('resume', models.CharField(blank=True, max_length=500, verbose_name='Résumé')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type', models.CharField(choices=[('INFORMATION', 'Information'), ('ANNONCE', 'Annonce'), ('ALERTE', 'Alerte'), ('RESULTAT', 'Résultat'), ('PROGRAMME', 'Programme'), ('PROMOTION', 'Promotion'), ('AUTRE', 'Autre')], db_index=True, default='INFORMATION', max_length=30)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMME', 'Programmé'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='communications/')),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('est_a_la_une', models.BooleanField(db_index=True, default=False)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-est_a_la_une', '-ordre_affichage', '-date_publication'],
                'indexes': [models.Index(fields=['statut', 'date_publication'], name='communicati_statut_f80952_idx'), models.Index(fields=['type', 'statut'], name='communicati_type_66997d_idx'), models.Index(fields=['est_a_la_une', 'statut'], name='communicati_est_a_l_74b70f_idx')],
            },
        ),
    ]
