# Generated by Django 5.2.17 on 2026-09-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('type', models.CharField(choices=[('AGENCE', 'Agence'), ('POINT_VENTE', 'Point de vente'), ('PMU_CLUB', 'PMU Club'), ('AUTRE', 'Autre')], db_index=True, default='POINT_VENTE', max_length=30)),
                ('ville', models.CharField(db_index=True, default='Ouagadougou', max_length=100)),
                ('quartier', models.CharField(blank=True, db_index=True, max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('est_principal', models.BooleanField(db_index=True, default=False)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_vente',
                'ordering': ['ville', 'quartier', 'nom'],
                'indexes': [models.Index(fields=['ville', 'quartier'], name='points_vent_ville_ae7cf9_idx'), models.Index(fields=['est_actif', 'ville'], name='points_vent_est_act_acafd2_idx'), models.Index(fields=['latitude', 'longitude'], name='points_vent_latitud_50b002_idx')],
            },
        ),
    ]
